# 카카오 로그인
kakao.rest-api-key=발급후입력
kakao.client-secret=발급후입력
kakao.redirect-uri=http://localhost:8088/beauty-dashboard/member/kakao/callback

# 네이버 로그인
naver.client-id=발급후입력
naver.client-secret=발급후입력
naver.redirect-uri=http://localhost:8088/beauty-dashboard/member/naver/callback
