# 카카오 로그인
kakao.rest-api-key=b3b9b89dc7d0087c254d6d53219805ad
kakao.client-secret=K0xLxZmTCXUFf2PdTAXZdG9OxMdtwMjJ
kakao.redirect-uri=http://localhost:8088/beauty-dashboard/member/kakao/callback

# 네이버 로그인
naver.client-id=발급후입력
naver.client-secret=발급후입력
naver.redirect-uri=http://localhost:8088/beauty-dashboard/member/naver/callback
